services:
  - type: web
    name: fiction-pipeline-reflex
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      reflex init
      reflex export --frontend-only --no-zip
    startCommand: reflex run --env prod --backend-only
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: API_URL
        value: https://fiction-pipeline-reflex.onrender.com

  - type: static
    name: fiction-pipeline-frontend
    env: static
    buildCommand: |
      pip install -r requirements.txt
      reflex init
      reflex export --frontend-only --no-zip
    staticPublishPath: .web/_static
    routes:
      - type: rewrite
        source: /api/*
        destination: https://fiction-pipeline-reflex.onrender.com/api/*
