services:
  - type: web
    name: fiction-pipeline-reflex
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      reflex init
    startCommand: reflex run --env prod --loglevel info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
