services:
  - type: web
    name: fiction-pipeline
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run web_ui.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
